# coding: utf-8

"""
    FIX Gateway Commander API

    # FIX Gateway Commander API REST API to get status and to send control commands to FIX Gateway.  Configuration API allows to view and update FIX Gateway session configuration.                         # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dmtsyganov@devexperts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sessions_response_inner import SessionsResponseInner  # noqa: E501
from swagger_client.rest import ApiException


class TestSessionsResponseInner(unittest.TestCase):
    """SessionsResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionsResponseInner(self):
        """Test SessionsResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sessions_response_inner.SessionsResponseInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
