# coding: utf-8

"""
    FIX Gateway Commander API

    # FIX Gateway Commander API REST API to get status and to send control commands to FIX Gateway.  Configuration API allows to view and update FIX Gateway session configuration.                         # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dmtsyganov@devexperts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.discovery_api import DiscoveryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self):
        self.api = DiscoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_discovery_agents_get(self):
        """Test case for discovery_agents_get

        Gets an agents data object  # noqa: E501
        """
        pass

    def test_discovery_sessions_get(self):
        """Test case for discovery_sessions_get

        Gets sessions data object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
