# coding: utf-8

"""
    FIX Gateway Commander API

    # FIX Gateway Commander API REST API to get status and to send control commands to FIX Gateway.  Configuration API allows to view and update FIX Gateway session configuration.                         # noqa: E501

    OpenAPI spec version: 0.1
    Contact: dmtsyganov@devexperts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LogoutRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_type': 'str',
        'initial': 'int',
        'name': 'str',
        'reset': 'bool'
    }

    attribute_map = {
        'agent_type': 'agentType',
        'initial': 'initial',
        'name': 'name',
        'reset': 'reset'
    }

    def __init__(self, agent_type=None, initial=None, name=None, reset=None):  # noqa: E501
        """LogoutRequest - a model defined in Swagger"""  # noqa: E501
        self._agent_type = None
        self._initial = None
        self._name = None
        self._reset = None
        self.discriminator = None
        if agent_type is not None:
            self.agent_type = agent_type
        if initial is not None:
            self.initial = initial
        if name is not None:
            self.name = name
        if reset is not None:
            self.reset = reset

    @property
    def agent_type(self):
        """Gets the agent_type of this LogoutRequest.  # noqa: E501

        Agent type - SERVER or CLIENT  # noqa: E501

        :return: The agent_type of this LogoutRequest.  # noqa: E501
        :rtype: str
        """
        return self._agent_type

    @agent_type.setter
    def agent_type(self, agent_type):
        """Sets the agent_type of this LogoutRequest.

        Agent type - SERVER or CLIENT  # noqa: E501

        :param agent_type: The agent_type of this LogoutRequest.  # noqa: E501
        :type: str
        """

        self._agent_type = agent_type

    @property
    def initial(self):
        """Gets the initial of this LogoutRequest.  # noqa: E501

        Initial sequence number  # noqa: E501

        :return: The initial of this LogoutRequest.  # noqa: E501
        :rtype: int
        """
        return self._initial

    @initial.setter
    def initial(self, initial):
        """Sets the initial of this LogoutRequest.

        Initial sequence number  # noqa: E501

        :param initial: The initial of this LogoutRequest.  # noqa: E501
        :type: int
        """

        self._initial = initial

    @property
    def name(self):
        """Gets the name of this LogoutRequest.  # noqa: E501

        Agent name  # noqa: E501

        :return: The name of this LogoutRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LogoutRequest.

        Agent name  # noqa: E501

        :param name: The name of this LogoutRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def reset(self):
        """Gets the reset of this LogoutRequest.  # noqa: E501

        Reset sequence number  # noqa: E501

        :return: The reset of this LogoutRequest.  # noqa: E501
        :rtype: bool
        """
        return self._reset

    @reset.setter
    def reset(self, reset):
        """Sets the reset of this LogoutRequest.

        Reset sequence number  # noqa: E501

        :param reset: The reset of this LogoutRequest.  # noqa: E501
        :type: bool
        """

        self._reset = reset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LogoutRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogoutRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
